version: 2.1

orbs:
  teak: teak/sdk-utils@dev:alpha

jobs:
  setup:
    docker:
      - image: cimg/base:2021.04

    steps:
      - teak/packer-install:
          version: 1.7.5

workflows:
  version: 2
  build-development:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - develop
      - teak/packer-build:
          version: 1.7.5
          name: "Generate Images (Development)"
          pre-steps:
            - run:
                command: sudo apt-get update && sudo apt-get install -y ansible awscli
          var: "region=us-east-1,environment=development"
          except: "vagrant.*"
          context: AWS-Write
          environment:
            PACKER_LOG: 1
          requires:
            - setup
  build-production:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - main
      - teak/packer-build:
          version: 1.7.5
          name: "Generate Images (Production)"
          pre-steps:
            - run:
                command: sudo apt-get update && sudo apt-get install -y ansible awscli
          var: "region=us-east-1,environment=production"
          except: "vagrant.*"
          context: AWS-Write
          requires:
            - setup
