# Copyright 2021 Teak.io, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- hosts: all
  become: yes

  tasks:
    - name: Ensure root directory structure exists
      file:
        path: '{{ item.path }}'
        state: directory
        owner: root
        group: root
        mode: 0755
      with_filetree: 'root'
      when: item.state == 'directory'

    - name: Copy/Template filesystem
      template:
        src: '{{ item.src }}'
        dest: '{{ item.path }}'
        owner: root
        group: root
        mode: 0644
      with_filetree: 'root'
      when: item.state == 'file'

    - name: Disable apt-daily
      systemd:
        name: "{{ item }}.timer"
        enabled: no
        state: stopped
      with_items:
        - apt-daily
        - apt-daily-upgrade

    - name: Enable systemd reload after cloud-init
      service:
        name: systemd-reload-after-cloud-init
        enabled: yes

    - name: Disable newrelic-infra
      service:
        name: newrelic-infra
        enabled: no

    - name: Enable Teak Log Aggregator
      service:
        name: teak-log-collector
        enabled: yes
        state: started

    - name: Enable Meta Configurator
      service:
        name: teak-metaconfigurator
        enabled: yes

    - name: Enable Configurator
      service:
        name: teak-configurator
        enabled: yes
