---
- hosts: all
  become: yes

  tasks:
    - name: Create fluentbit User
      register: fluentbit_user
      user:
        name: fluentbit
        create_home: no
        shell: /sbin/nologin
        password: "!"
        system: yes
        groups:
          - systemd-journal

    - name: Add FluentBit APT key
      copy:
        src: data/fluentbit.key
        dest: /usr/share/keyrings/fluentbit-archive-keyring.gpg
        owner: root
        group: root
        mode: 0644

    - name: Add FluentBit APT Repo
      copy:
        dest: /etc/apt/sources.list.d/packages_fluentbit_io_debian_buster.list
        owner: root
        group: root
        mode: 0644
        content: deb [signed-by=/usr/share/keyrings/fluentbit-archive-keyring.gpg] https://packages.fluentbit.io/debian/buster buster main

    - name: Install FluentBit
      apt:
        install_recommends: no
        state: present
        update_cache: yes
        name:
          - td-agent-bit

    - name: Remove FluentBit APT key
      file:
        path: /usr/share/keyrings/fluentbit-archive-keyring.gpg
        state: absent

    - name: Remove FluentBit APT Repo
      file:
        path: /etc/apt/sources.list.d/packages_fluentbit_io_debian_buster.list
        state: absent

    - name: Create FluentBit Config Base Dir
      register: fluentbit_base
      file:
        path: /etc/teak-log-collector
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Create FluentBit Config Dir
      register: fluentbit_confdir
      file:
        path: "{{ fluentbit_base.path }}/conf.d"
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Create FluentBit Builtin Parsers
      register: fluentbit_builtin_parsers
      template:
        src: data/parsers.conf
        dest: "{{ fluentbit_base.path }}/00_builtin_parsers.conf"
        owner: root
        group: root
        mode: 0644

    - name: Create FluentBit Builtin Plugins
      register: fluentbit_builtin_plugins
      template:
        src: data/plugins.conf
        dest: "{{ fluentbit_base.path }}/00_builtin_plugins.conf"
        owner: root
        group: root
        mode: 0644

    - name: Create FluentBit Service Parsers
      register: fluentbit_service_parsers
      copy:
        content: "# Parsers for a specific service go here"
        dest: "{{ fluentbit_base.path }}/10_service_parsers.conf"
        owner: root
        group: root
        mode: 0644

    - name: Create FluentBit Service Plugins
      register: fluentbit_service_plugins
      copy:
        content: "# Plugins for a specific service go here"
        dest: "{{ fluentbit_base.path }}/10_service_plugins.conf"
        owner: root
        group: root
        mode: 0644

    - name: Create FluentBit Env Input
      copy:
        content: "# SET parameters here in order to configure the environment"
        dest: "{{ fluentbit_confdir.path }}/00_environment.conf"
        owner: root
        group: root
        mode: 0644

    - name: Create FluentBit Standard Inputs
      template:
        src: data/10_standard_in.conf
        dest: "{{ fluentbit_confdir.path }}/10_standard_in.conf"
        owner: root
        group: root
        mode: 0644

    - name: Create FluentBit Standard Outputs
      template:
        src: data/20_standard_out.conf
        dest: "{{ fluentbit_confdir.path }}/20_standard_out.conf"
        owner: root
        group: root
        mode: 0644

    - name: Update FluentBit config
      register: fluentbit_config
      template:
        src: data/td-agent-bit.conf
        dest: "{{ fluentbit_base.path }}/teak-log-collector.conf"
        owner: root
        group: root
        mode: 0644

    - name: Update FluentBit service config
      template:
        src: data/teak-log-collector.service
        dest: /lib/systemd/system/teak-log-collector.service
        owner: root
        group: root
        mode: 0644

    - name: Configure FluentBit Logrotate
      template:
        src: data/fluentbit-logrotate.conf
        dest: /etc/logrotate.d/teak-log-collector
        owner: root
        group: root
        mode: 0644

    - name: Disable Stock FluentBit
      service:
        name: td-agent-bit
        enabled: no

    - name: Remove stock FluentBit files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /lib/systemd/system/td-agent-bit.service
        - /etc/td-agent-bit/

    - name: Enable Teak Log Aggregator
      service:
        name: teak-log-collector
        enabled: yes
        state: started
